dev:
  build: .
  command: /sbin/my_init
  ports:
   - "8000:8000"
   - "8080:8080"
   - "9876:9876"
  volumes:
   - ".:/vagrant"
   - ".:/vagrant_bind"
   - "./provision/docker/mysql:/etc/mysql/conf.d"
  privileged: true
  environment:
   - PYTHONDONTWRITEBYTECODE=true
   - NODE_PATH=/vagrant-dev/node_modules/


